
SELECT
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE * (1 - CD.DISCOUNT_RATE * 0.01) * 30) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR AS C
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CD ON C.CAR_TYPE = CD.CAR_TYPE
WHERE
    C.CAR_TYPE IN ('세단', 'SUV')
    AND
    C.CAR_ID NOT IN 
    (
        SELECT
            CAR_ID
        FROM
            CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE
            START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
    AND
    CD.DURATION_TYPE = '30일 이상'
HAVING
    FEE >= 500000 AND FEE < 2000000
ORDER BY
    FEE DESC, C.CAR_TYPE ASC, C.CAR_ID DESC
