-- 코드를 입력하세요
SELECT
    F.PRODUCT_ID as 'PRODUCT_ID',
    F.PRODUCT_NAME as 'PRODUCT_NAME',
    SUM(O.AMOUNT) * F.PRICE as 'TOTAL_SALES'
FROM FOOD_PRODUCT as F
LEFT JOIN FOOD_ORDER as O ON F.PRODUCT_ID = O.PRODUCT_ID
WHERE 1=1
    AND year(O.PRODUCE_DATE) = 2022
    AND month(O.PRODUCE_DATE) = 5
GROUP BY (F.PRODUCT_NAME)
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
