SELECT
    year(DIFFERENTIATION_DATE) as 'YEAR',
    (SELECT MAX(SIZE_OF_COLONY)
        FROM ECOLI_DATA
           WHERE YEAR = year(DIFFERENTIATION_DATE)
     ) - SIZE_OF_COLONY as 'YEAR_DEV',
    ID as 'ID'
FROM ECOLI_DATA as ED
ORDER BY YEAR ASC, YEAR_DEV ASC;