-- 코드를 작성해주세요
SELECT
    SUB.YEAR,
    abs(MAX_SIZE - SIZE_OF_COLONY) as 'YEAR_DEV',
    ID
FROM
    ECOLI_DATA as MAIN
JOIN
    (
    SELECT
        max(SIZE_OF_COLONY) as 'MAX_SIZE',
        year(DIFFERENTIATION_DATE) as 'YEAR'
    FROM
        ECOLI_DATA
    GROUP BY
        year(DIFFERENTIATION_DATE)
    ) as SUB ON year(MAIN.DIFFERENTIATION_DATE) = SUB.YEAR
ORDER BY
    YEAR ASC, YEAR_DEV ASC;