SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM FISH_INFO as FI
JOIN FISH_NAME_INFO as FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
WHERE FI.LENGTH = (
    SELECT
        MAX(LENGTH)
    FROM FISH_INFO
    WHERE FI.FISH_TYPE = FISH_TYPE
)
ORDER BY ID;