SELECT
    ID,
    FISH_NAME,
    LENGTH
FROM
    FISH_INFO as F
JOIN
    FISH_NAME_INFO as N ON F.FISH_TYPE = N.FISH_TYPE
WHERE
    LENGTH = (
        SELECT
            MAX(LENGTH)
        FROM FISH_INFO
        WHERE FISH_TYPE = F.FISH_TYPE
    )
ORDER BY
    ID ASC;